apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kuma-heartbeat
  labels:
    name: kuma-heartbeat
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  kuma-heartbeat
    spec:
      containers:
      - name: kuma-heartbeat
        image: jsonfry/curl-cron:latest
        imagePullPolicy: Always
        env:
          - name: OPTIONS
            value: "https://status.themikkel.dk/api/push/AJbz7GZ4cR?status=up&msg=OK&ping="
          - name: CRON_SCHEDULE
            value: "*/30 * * * *"
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 16Mi
        imagePullSecrets:
          - name: sdugitlab
